name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # run the workflow on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # ?
      - name: Checkout code
        uses: actions/checkout@v2

      # docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # ?
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/backend.dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      # build and push frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/frontend.dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      # build and push db
      - name: Push Postgres image
        run: |
          docker pull postgres:12  # Pull the official Postgres image from Docker Hub
          docker tag postgres:12 ${{ secrets.DOCKER_HUB_USERNAME }}/db:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/db:latest
